import { createFileRoute } from "@tanstack/react-router";

const TITLE = "Research in Development — Dr. Åke Elden";
const DESCRIPTION =
  "Ongoing research projects, conceptual papers, and philosophical investigations in progress — organised by theme across philosophy of science, artificial intelligence, and technology & society.";
const URL_SELF = "https://ake-elden-archive.lovable.app/working-papers";

export const Route = createFileRoute("/working-papers")({
  head: () => ({
    meta: [
      { title: TITLE },
      { name: "description", content: DESCRIPTION },
      { property: "og:title", content: TITLE },
      { property: "og:description", content: DESCRIPTION },
      { property: "og:url", content: URL_SELF },
      { property: "og:type", content: "website" },
    ],
    links: [{ rel: "canonical", href: URL_SELF }],
    scripts: [
      {
        type: "application/ld+json",
        children: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "CollectionPage",
          url: URL_SELF,
          name: TITLE,
          description: DESCRIPTION,
          about: { "@type": "Person", name: "Åke Elden" },
        }),
      },
    ],
  }),
  component: WorkingPapersPage,
});

type Paper = {
  title: string;
  status: string;
  summary: string;
  keywords?: string[];
};

type Theme = {
  name: string;
  papers: Paper[];
};

const THEMES: Theme[] = [
  {
    name: "Philosophy of Science",
    papers: [
      {
        title:
          "Constitutive License: Object Constitution and the Limits of Scientific Inference",
        status: "Working Paper",
        summary:
          "Argues that philosophy of science lacks a general account of how the constitution of scientific objects determines the inferential scope of empirical research. Introduces the Inheritance Principle — inferential scope is inherited from object constitution rather than generated by evidence alone — and develops constitutive license, constitutive non-self-sufficiency, and constitutive overreach as consequences.",
        keywords: [
          "Philosophy of science",
          "Scientific inference",
          "Measurement",
          "Object constitution",
          "Epistemology",
        ],
      },
      {
        title: "Inferential License",
        status: "Conceptual Paper",
        summary:
          "Every empirical design carries an inferential license that defines which conclusions are justified by the design employed. Scientific error begins when claims exceed that license. Develops a general account applicable to AI, psychology, medicine, and the social sciences.",
      },
      {
        title: "Evidence Is Not Ground",
        status: "Discussion Paper",
        summary:
          "Evidence supports claims only within a previously constituted conceptual framework. Evidence cannot by itself establish the adequacy of the framework that gives it meaning.",
      },
    ],
  },
  {
    name: "Artificial Intelligence",
    papers: [
      {
        title: "Epistemic Infrastructure",
        status: "Working Paper",
        summary:
          "Artificial intelligence increasingly functions as infrastructure for knowledge production rather than merely as a tool. Explores how AI reorganises attention, memory, justification, and institutional knowledge.",
      },
      {
        title: "Administrative Epistemic Lag",
        status: "Working Paper",
        summary:
          "Governance often regulates emerging technologies using inherited conceptual categories developed for previous technological eras. Argues that accumulated administrative expertise can itself become a source of epistemic lag.",
      },
      {
        title: "Benchmark Success and Constitutive Overreach",
        status: "Research Note",
        summary:
          "Explores why benchmark improvements are frequently interpreted as evidence for broader capabilities than the benchmark actually licenses.",
      },
    ],
  },
  {
    name: "Technology and Society",
    papers: [
      {
        title: "Philosophy of Formation",
        status: "Conceptual Project",
        summary:
          "Investigates human formation under conditions of algorithmic mediation and optimisation, connecting philosophical anthropology, ethics, education, and AI.",
      },
      {
        title: "Maintenance Before Innovation",
        status: "Working Paper",
        summary:
          "Argues that philosophy of technology has disproportionately emphasised innovation while neglecting maintenance, repair, and infrastructural continuity.",
      },
    ],
  },
];

const CONCEPTUAL_NOTES = [
  "Constitutive Silence",
  "Epistemic Automation",
  "Determinant Substitution",
  "Proxy Ontology",
  "Institutional Friction",
  "Object Constitution",
  "Inferential Scope",
  "Explanation Beyond Measurement",
];

function WorkingPapersPage() {
  return (
    <div>
      {/* Intro */}
      <section className="border-b border-border">
        <div className="mx-auto max-w-3xl px-6 py-20 lg:px-8">
          <p className="text-xs font-medium uppercase tracking-[0.2em] text-muted-foreground">
            Research in Development
          </p>
          <h1 className="mt-3 font-display text-4xl leading-[1.1] text-foreground md:text-5xl">
            A selection of ongoing research projects
          </h1>
          <p className="mt-8 text-base leading-relaxed text-foreground/85">
            A selection of ongoing research projects, conceptual papers, and
            philosophical investigations. These manuscripts are works in
            progress intended to develop new research directions before journal
            submission. Titles and abstracts may evolve as the projects mature.
          </p>
          <p className="mt-6 text-base leading-relaxed text-foreground/85">
            My research focuses on the conceptual foundations of science,
            artificial intelligence, and technological society. Across these
            domains I investigate the conditions that make inference,
            responsibility, explanation, and institutional knowledge possible.
            Rather than treating philosophy of science, AI ethics, and
            philosophy of technology as separate disciplines, my work seeks
            general principles that recur across them — with particular
            attention to the relationship between object constitution,
            inference, and human judgment.
          </p>
        </div>
      </section>

      {/* Themes */}
      {THEMES.map((theme, ti) => (
        <section
          key={theme.name}
          className={
            "border-b border-border " + (ti % 2 === 0 ? "bg-muted/30" : "")
          }
        >
          <div className="mx-auto max-w-3xl px-6 py-20 lg:px-8">
            <p className="text-xs font-medium uppercase tracking-[0.2em] text-muted-foreground">
              Theme
            </p>
            <h2 className="mt-3 font-display text-3xl text-foreground md:text-4xl">
              {theme.name}
            </h2>

            <div className="mt-10 space-y-12">
              {theme.papers.map((p) => (
                <article
                  key={p.title}
                  className="border-t border-border pt-6"
                >
                  <div className="flex flex-wrap items-baseline justify-between gap-3">
                    <h3 className="font-display text-xl leading-snug text-foreground md:text-2xl">
                      {p.title}
                    </h3>
                    <span className="inline-flex items-center rounded-sm border border-border bg-background px-2 py-0.5 text-[0.7rem] font-medium uppercase tracking-[0.18em] text-muted-foreground">
                      {p.status}
                    </span>
                  </div>
                  <p className="mt-4 text-base leading-relaxed text-foreground/85">
                    {p.summary}
                  </p>
                  {p.keywords && (
                    <p className="mt-4 text-xs text-muted-foreground">
                      <span className="font-medium uppercase tracking-[0.2em]">
                        Keywords
                      </span>{" "}
                      · {p.keywords.join(" • ")}
                    </p>
                  )}
                </article>
              ))}
            </div>
          </div>
        </section>
      ))}

      {/* Conceptual Notes */}
      <section className="border-b border-border">
        <div className="mx-auto max-w-3xl px-6 py-20 lg:px-8">
          <p className="text-xs font-medium uppercase tracking-[0.2em] text-muted-foreground">
            Conceptual Notes
          </p>
          <h2 className="mt-3 font-display text-3xl text-foreground md:text-4xl">
            Smaller ideas in development
          </h2>
          <p className="mt-6 text-base leading-relaxed text-foreground/85">
            A short section for smaller ideas that may later become full papers.
          </p>
          <ul className="mt-8 grid grid-cols-1 gap-x-8 gap-y-2 sm:grid-cols-2">
            {CONCEPTUAL_NOTES.map((n) => (
              <li
                key={n}
                className="border-t border-border py-3 font-display text-base text-foreground/85"
              >
                {n}
              </li>
            ))}
          </ul>
        </div>
      </section>

      {/* Note on discussion papers */}
      <section>
        <div className="mx-auto max-w-3xl px-6 py-20 lg:px-8">
          <div className="border-l-2 border-foreground/40 pl-6">
            <p className="text-xs font-medium uppercase tracking-[0.2em] text-muted-foreground">
              A note on these manuscripts
            </p>
            <p className="mt-3 font-display text-lg italic leading-snug text-foreground/85 md:text-xl">
              These manuscripts are shared to document ongoing research and
              encourage scholarly discussion. They should be regarded as work
              in progress unless otherwise indicated.
            </p>
          </div>
        </div>
      </section>
    </div>
  );
}
