/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThemesRouteImport } from './routes/themes'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as NewsRouteImport } from './routes/news'
import { Route as CvRouteImport } from './routes/cv'
import { Route as CurrentResearchRouteImport } from './routes/current-research'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConceptGraphRouteImport } from './routes/concept-graph'
import { Route as AcademicProfileRouteImport } from './routes/academic-profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConceptsIndexRouteImport } from './routes/concepts.index'
import { Route as ThemesSlugRouteImport } from './routes/themes.$slug'
import { Route as ConceptsSlugRouteImport } from './routes/concepts.$slug'

const ThemesRoute = ThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrentResearchRoute = CurrentResearchRouteImport.update({
  id: '/current-research',
  path: '/current-research',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptGraphRoute = ConceptGraphRouteImport.update({
  id: '/concept-graph',
  path: '/concept-graph',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicProfileRoute = AcademicProfileRouteImport.update({
  id: '/academic-profile',
  path: '/academic-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptsIndexRoute = ConceptsIndexRouteImport.update({
  id: '/concepts/',
  path: '/concepts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesSlugRoute = ThemesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ThemesRoute,
} as any)
const ConceptsSlugRoute = ConceptsSlugRouteImport.update({
  id: '/concepts/$slug',
  path: '/concepts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academic-profile': typeof AcademicProfileRoute
  '/concept-graph': typeof ConceptGraphRoute
  '/contact': typeof ContactRoute
  '/current-research': typeof CurrentResearchRoute
  '/cv': typeof CvRoute
  '/news': typeof NewsRoute
  '/projects': typeof ProjectsRoute
  '/publications': typeof PublicationsRoute
  '/research': typeof ResearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/themes': typeof ThemesRouteWithChildren
  '/concepts/$slug': typeof ConceptsSlugRoute
  '/themes/$slug': typeof ThemesSlugRoute
  '/concepts/': typeof ConceptsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academic-profile': typeof AcademicProfileRoute
  '/concept-graph': typeof ConceptGraphRoute
  '/contact': typeof ContactRoute
  '/current-research': typeof CurrentResearchRoute
  '/cv': typeof CvRoute
  '/news': typeof NewsRoute
  '/projects': typeof ProjectsRoute
  '/publications': typeof PublicationsRoute
  '/research': typeof ResearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/themes': typeof ThemesRouteWithChildren
  '/concepts/$slug': typeof ConceptsSlugRoute
  '/themes/$slug': typeof ThemesSlugRoute
  '/concepts': typeof ConceptsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academic-profile': typeof AcademicProfileRoute
  '/concept-graph': typeof ConceptGraphRoute
  '/contact': typeof ContactRoute
  '/current-research': typeof CurrentResearchRoute
  '/cv': typeof CvRoute
  '/news': typeof NewsRoute
  '/projects': typeof ProjectsRoute
  '/publications': typeof PublicationsRoute
  '/research': typeof ResearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/themes': typeof ThemesRouteWithChildren
  '/concepts/$slug': typeof ConceptsSlugRoute
  '/themes/$slug': typeof ThemesSlugRoute
  '/concepts/': typeof ConceptsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academic-profile'
    | '/concept-graph'
    | '/contact'
    | '/current-research'
    | '/cv'
    | '/news'
    | '/projects'
    | '/publications'
    | '/research'
    | '/sitemap.xml'
    | '/themes'
    | '/concepts/$slug'
    | '/themes/$slug'
    | '/concepts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academic-profile'
    | '/concept-graph'
    | '/contact'
    | '/current-research'
    | '/cv'
    | '/news'
    | '/projects'
    | '/publications'
    | '/research'
    | '/sitemap.xml'
    | '/themes'
    | '/concepts/$slug'
    | '/themes/$slug'
    | '/concepts'
  id:
    | '__root__'
    | '/'
    | '/academic-profile'
    | '/concept-graph'
    | '/contact'
    | '/current-research'
    | '/cv'
    | '/news'
    | '/projects'
    | '/publications'
    | '/research'
    | '/sitemap.xml'
    | '/themes'
    | '/concepts/$slug'
    | '/themes/$slug'
    | '/concepts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademicProfileRoute: typeof AcademicProfileRoute
  ConceptGraphRoute: typeof ConceptGraphRoute
  ContactRoute: typeof ContactRoute
  CurrentResearchRoute: typeof CurrentResearchRoute
  CvRoute: typeof CvRoute
  NewsRoute: typeof NewsRoute
  ProjectsRoute: typeof ProjectsRoute
  PublicationsRoute: typeof PublicationsRoute
  ResearchRoute: typeof ResearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ThemesRoute: typeof ThemesRouteWithChildren
  ConceptsSlugRoute: typeof ConceptsSlugRoute
  ConceptsIndexRoute: typeof ConceptsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/themes': {
      id: '/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/current-research': {
      id: '/current-research'
      path: '/current-research'
      fullPath: '/current-research'
      preLoaderRoute: typeof CurrentResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept-graph': {
      id: '/concept-graph'
      path: '/concept-graph'
      fullPath: '/concept-graph'
      preLoaderRoute: typeof ConceptGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic-profile': {
      id: '/academic-profile'
      path: '/academic-profile'
      fullPath: '/academic-profile'
      preLoaderRoute: typeof AcademicProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concepts/': {
      id: '/concepts/'
      path: '/concepts'
      fullPath: '/concepts/'
      preLoaderRoute: typeof ConceptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes/$slug': {
      id: '/themes/$slug'
      path: '/$slug'
      fullPath: '/themes/$slug'
      preLoaderRoute: typeof ThemesSlugRouteImport
      parentRoute: typeof ThemesRoute
    }
    '/concepts/$slug': {
      id: '/concepts/$slug'
      path: '/concepts/$slug'
      fullPath: '/concepts/$slug'
      preLoaderRoute: typeof ConceptsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ThemesRouteChildren {
  ThemesSlugRoute: typeof ThemesSlugRoute
}

const ThemesRouteChildren: ThemesRouteChildren = {
  ThemesSlugRoute: ThemesSlugRoute,
}

const ThemesRouteWithChildren =
  ThemesRoute._addFileChildren(ThemesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademicProfileRoute: AcademicProfileRoute,
  ConceptGraphRoute: ConceptGraphRoute,
  ContactRoute: ContactRoute,
  CurrentResearchRoute: CurrentResearchRoute,
  CvRoute: CvRoute,
  NewsRoute: NewsRoute,
  ProjectsRoute: ProjectsRoute,
  PublicationsRoute: PublicationsRoute,
  ResearchRoute: ResearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ThemesRoute: ThemesRouteWithChildren,
  ConceptsSlugRoute: ConceptsSlugRoute,
  ConceptsIndexRoute: ConceptsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
